sudo: false
language: php
php:
  - '7.0'
  - nightly
cache:
  directories:
    - $HOME/.cache/composer/files
install:
  - composer selfupdate
  - composer install
  - curl -LSs https://box-project.github.io/box2/installer.php | php
script:
  - php box.phar build
